export type ProgramType = "fellowship" | "accelerator" | "vc" | "grant" | "corporate"
export type ApplicationStatus = "not_started" | "drafting" | "submitted" | "interviewing" | "accepted" | "rejected"

export interface FundingQuestion {
  id: string
  label: string
  placeholder: string
  maxWords?: number
  type: "textarea" | "short" | "url" | "number"
}

export interface VCContact {
  name: string
  role: string
  email?: string          // leave blank if not publicly known
  linkedin?: string       // handle only, e.g. "johndoe"
  twitter?: string        // handle only, e.g. "johndoe"
  note?: string           // e.g. "leads proptech deals", "India partner"
}

export interface FundingProgram {
  id: string
  name: string
  shortName: string
  type: ProgramType
  description: string
  amount: string
  equity: string
  deadline: string
  location: string
  stage: string
  focusAreas: string[]
  applyUrl: string
  contacts: VCContact[]
  questions: FundingQuestion[]
  tips: string[]
  color: string
  emoji: string
}

export const PROPSTICAL_CONTEXT = {
  company: "Propstical",
  tagline: "India's first AI home decision canvas",
  problem: "The average Indian homeowner wastes ₹2.1 Lakh on renovation mistakes they could have caught before signing. Decisions are made from scattered WhatsApp screenshots, contractor quotes on paper, and inspiration images across 3 apps — with no unified view.",
  solution: "Propstical Canvas is a spatial AI pre-decision tool. Homeowners drop renovation variables — materials, quotes, room dimensions, budget, design inspiration, contractor concerns — onto a visual canvas. AI classifies them into 14 types, detects hidden conflicts (marble choice vs. budget, layout vs. room dimensions, quote gaps vs. specs), and surfaces a single critical insight to prevent costly mistakes.",
  market: "India's home renovation market is $20B and growing at 12% YoY. 11 million urban households renovate annually. Zero tools exist for the pre-decision phase — all current tools (Houzz, Livspace) target post-decision execution.",
  traction: "Live product at propstical.com/canvas. WhatsApp & Telegram bot integrations for mobile note capture. 14-type AI classification system. Three synchronized views: Tiling, Kanban, and Force-directed Graph. 100% browser-based, no signup required.",
  team: "Nevil Parekh — Founder. Building at the intersection of AI and the Indian home renovation market.",
  techStack: "Next.js 16, React 19, TypeScript, Tailwind CSS v4, Claude Sonnet via OpenRouter, D3.js force graphs, Supabase",
  businessModel: "Freemium SaaS: free canvas for homeowners, paid tiers for contractors and interior designers who manage multiple projects. B2B2C channel through design studios.",
  vision: "Every major home decision in India — renovation, purchase, rental — should happen through Propstical. We are the pre-commitment intelligence layer for the Indian real estate ecosystem.",
  founders: "India-based, building for the Indian urban homeowner. Deep domain expertise in the renovation decision journey.",
  raise: "Seeking seed funding to scale product, grow to 10,000 active homeowners, and build the contractor/designer B2B channel.",
}

export const FUNDING_PROGRAMS: FundingProgram[] = [
  {
    id: "yc",
    name: "Y Combinator",
    shortName: "YC",
    type: "accelerator",
    description: "The world's most prestigious startup accelerator. YC companies have gone on to be worth over $600B combined.",
    amount: "$500K",
    equity: "7%",
    deadline: "Rolling (W26: Oct 2025)",
    location: "San Francisco, CA (remote ok)",
    stage: "Pre-seed to Seed",
    focusAreas: ["B2B SaaS", "Consumer", "AI/ML", "Proptech", "India"],
    applyUrl: "https://www.ycombinator.com/apply",
    color: "orange",
    emoji: "🔶",
    tips: [
      "YC loves founders who have a unique insight the market hasn't seen",
      "Emphasize speed: what have you built in how little time",
      "Market size must be defensible — show you've done the math",
      "Video should be authentic, not scripted",
    ],
    questions: [
      { id: "yc_q1", label: "Describe your company in 50 characters or less.", placeholder: "AI canvas for India home renovation", maxWords: 15, type: "short" },
      { id: "yc_q2", label: "What is your company going to make?", placeholder: "Describe what you build and for whom...", maxWords: 150, type: "textarea" },
      { id: "yc_q3", label: "Why did you pick this idea to work on? Do you have domain expertise in this area?", placeholder: "Share the founder story and insight...", maxWords: 200, type: "textarea" },
      { id: "yc_q4", label: "Who are your competitors and what makes you different?", placeholder: "Describe the competitive landscape...", maxWords: 200, type: "textarea" },
      { id: "yc_q5", label: "What do you understand about your users that most founders in your space don't get?", placeholder: "Your unique insight...", maxWords: 200, type: "textarea" },
      { id: "yc_q6", label: "What's the size of your market?", placeholder: "Bottom-up or top-down analysis...", maxWords: 150, type: "textarea" },
      { id: "yc_q7", label: "How do you plan to get your first 100 customers?", placeholder: "Concrete go-to-market plan...", maxWords: 150, type: "textarea" },
      { id: "yc_q8", label: "What is your current monthly revenue? What is your monthly growth rate?", placeholder: "Honest traction numbers...", maxWords: 100, type: "textarea" },
      { id: "yc_q9", label: "What's the biggest risk or obstacle to your company's success?", placeholder: "Be honest about what keeps you up at night...", maxWords: 150, type: "textarea" },
    ],
  },
  {
    id: "ef",
    name: "Entrepreneur First",
    shortName: "EF",
    type: "fellowship",
    description: "EF backs exceptional individuals before they have a company, helping them find co-founders and build from scratch.",
    amount: "£80K–£150K",
    equity: "8–10%",
    deadline: "Rolling cohorts (Bangalore: 2x/year)",
    location: "Bangalore / London / Singapore",
    stage: "Pre-idea to Pre-seed",
    focusAreas: ["Deep Tech", "AI", "B2B", "Individual talent"],
    applyUrl: "https://www.joinef.com/apply",
    color: "blue",
    emoji: "🔵",
    tips: [
      "EF bets on YOU as an individual, not the idea",
      "Emphasize what makes you an 'outlier' — your edge, not just credentials",
      "Show intellectual curiosity and ability to learn fast",
      "Be honest about co-founder needs",
    ],
    questions: [
      { id: "ef_q1", label: "Tell us about yourself and why you want to start a company.", placeholder: "Your story, drive, and ambition...", maxWords: 300, type: "textarea" },
      { id: "ef_q2", label: "What is your edge? What do you know or can do that most people can't?", placeholder: "Your unique expertise or unfair advantage...", maxWords: 200, type: "textarea" },
      { id: "ef_q3", label: "Describe a time when you took a significant risk. What happened?", placeholder: "A story of bold action...", maxWords: 200, type: "textarea" },
      { id: "ef_q4", label: "What problem do you want to work on and why does it matter?", placeholder: "The problem space you're obsessed with...", maxWords: 200, type: "textarea" },
      { id: "ef_q5", label: "What would make you a great co-founder to work with?", placeholder: "Your strengths and working style...", maxWords: 150, type: "textarea" },
      { id: "ef_q6", label: "What are 3 things you've built, created, or shipped that you're most proud of?", placeholder: "Concrete examples of your output...", maxWords: 200, type: "textarea" },
    ],
  },
  {
    id: "thiel",
    name: "Thiel Fellowship",
    shortName: "Thiel",
    type: "fellowship",
    description: "The Thiel Fellowship gives $100K to young people under 23 to skip or stop out of college and build something great.",
    amount: "$100K",
    equity: "0%",
    deadline: "Annual (Dec–Jan)",
    location: "Global (US-centric)",
    stage: "Individual / Pre-company",
    focusAreas: ["Science", "Tech", "Social innovation", "Under 23"],
    applyUrl: "https://thielfellowship.org/apply",
    color: "purple",
    emoji: "🟣",
    tips: [
      "Thiel funds contrarians — people who believe something true that most don't",
      "Show you'd be better off NOT in school",
      "Intellectual depth matters as much as execution",
      "The 'secret' — your non-consensus insight — is the heart of the application",
    ],
    questions: [
      { id: "thiel_q1", label: "Describe your project/company in 1–2 sentences.", placeholder: "Clear and bold description...", maxWords: 50, type: "textarea" },
      { id: "thiel_q2", label: "What important truth do very few people agree with you on?", placeholder: "Your contrarian insight...", maxWords: 300, type: "textarea" },
      { id: "thiel_q3", label: "Why is now the right time to build this?", placeholder: "The timing thesis...", maxWords: 200, type: "textarea" },
      { id: "thiel_q4", label: "What have you already built or done? Show us your work.", placeholder: "Concrete proof of progress...", maxWords: 250, type: "textarea" },
      { id: "thiel_q5", label: "Why would you be better off not in school right now?", placeholder: "The opportunity cost argument...", maxWords: 200, type: "textarea" },
      { id: "thiel_q6", label: "If successful, what does this look like in 20 years?", placeholder: "The long-term vision...", maxWords: 200, type: "textarea" },
    ],
  },
  {
    id: "a16z_speedrun",
    name: "a16z Speedrun",
    shortName: "Speedrun",
    type: "accelerator",
    description: "Andreessen Horowitz's 8-week program for pre-seed AI consumer startups, with potential follow-on investment.",
    amount: "$750K–$1M",
    equity: "4–7%",
    deadline: "Cohort-based (2x/year)",
    location: "San Francisco, CA",
    stage: "Pre-seed, AI-first",
    focusAreas: ["AI Consumer", "AI SaaS", "Viral products"],
    applyUrl: "https://speedrun.a16z.com",
    color: "green",
    emoji: "🟢",
    tips: [
      "a16z loves products that use AI in a genuinely new way, not just GPT wrappers",
      "Show strong founder-market fit and product intuition",
      "Consumer virality is a big plus",
      "Demonstrate you understand the AI landscape deeply",
    ],
    questions: [
      { id: "a16z_q1", label: "Describe your product in 2–3 sentences.", placeholder: "What it is and who it's for...", maxWords: 75, type: "textarea" },
      { id: "a16z_q2", label: "What's the core AI innovation that makes your product possible?", placeholder: "The AI insight or technique...", maxWords: 200, type: "textarea" },
      { id: "a16z_q3", label: "Who is your target user and why will they love this?", placeholder: "User persona and value prop...", maxWords: 200, type: "textarea" },
      { id: "a16z_q4", label: "What does your growth look like today?", placeholder: "Users, engagement, retention data...", maxWords: 150, type: "textarea" },
      { id: "a16z_q5", label: "How do you acquire users?", placeholder: "Channels and CAC...", maxWords: 150, type: "textarea" },
      { id: "a16z_q6", label: "Why are you the right team to build this?", placeholder: "Team background and edge...", maxWords: 150, type: "textarea" },
    ],
  },
  {
    id: "antler",
    name: "Antler",
    shortName: "Antler",
    type: "accelerator",
    description: "Antler is a global early-stage VC that invests from day zero, helping founders find co-founders and validate ideas.",
    amount: "$100K–$250K",
    equity: "8–12%",
    deadline: "Rolling (India: Bangalore)",
    location: "Bangalore / Global 30+ cities",
    stage: "Pre-idea to Pre-seed",
    focusAreas: ["B2B SaaS", "Fintech", "Climate", "AI", "India"],
    applyUrl: "https://www.antler.co/apply",
    color: "red",
    emoji: "🔴",
    tips: [
      "Antler is open to founders at any stage of ideation",
      "Show you're a strong executor who moves fast",
      "India cohort has strong proptech and B2B SaaS appetite",
      "Co-founder matching is a core part of the program",
    ],
    questions: [
      { id: "antler_q1", label: "Tell us about yourself and your background.", placeholder: "Professional and personal story...", maxWords: 200, type: "textarea" },
      { id: "antler_q2", label: "What startup idea are you most excited about building?", placeholder: "Your current hypothesis...", maxWords: 200, type: "textarea" },
      { id: "antler_q3", label: "Why do you want to start a company now?", placeholder: "Motivation and timing...", maxWords: 150, type: "textarea" },
      { id: "antler_q4", label: "What's your superpower as a founder?", placeholder: "Your unique strength...", maxWords: 150, type: "textarea" },
      { id: "antler_q5", label: "What have you built previously? Any entrepreneurial experience?", placeholder: "Past projects and ventures...", maxWords: 200, type: "textarea" },
    ],
  },
  {
    id: "surge",
    name: "Surge by Sequoia",
    shortName: "Surge",
    type: "accelerator",
    description: "Sequoia Capital's rapid scale-up program for startups in India and Southeast Asia.",
    amount: "$1–2M",
    equity: "10–15%",
    deadline: "Annual (applications open Feb)",
    location: "India / SEA",
    stage: "Early-stage, some traction",
    focusAreas: ["India", "SEA", "SaaS", "Consumer", "Fintech", "AI"],
    applyUrl: "https://www.surgeahead.com/apply",
    color: "teal",
    emoji: "🌊",
    tips: [
      "Surge loves India-native insights — deep market knowledge wins",
      "Some traction or early users is expected",
      "Show you understand unit economics from day one",
      "Sequoia backs category-defining companies — think big",
    ],
    questions: [
      { id: "surge_q1", label: "Describe your startup in 3 sentences.", placeholder: "Product, market, and insight...", maxWords: 100, type: "textarea" },
      { id: "surge_q2", label: "What problem are you solving and why does it matter in India/SEA?", placeholder: "The regional problem statement...", maxWords: 250, type: "textarea" },
      { id: "surge_q3", label: "What is your traction so far?", placeholder: "Users, revenue, growth metrics...", maxWords: 150, type: "textarea" },
      { id: "surge_q4", label: "What's your business model and path to profitability?", placeholder: "Revenue model and unit economics...", maxWords: 200, type: "textarea" },
      { id: "surge_q5", label: "Why is your team uniquely positioned to win in this market?", placeholder: "Domain expertise and founder-market fit...", maxWords: 200, type: "textarea" },
      { id: "surge_q6", label: "What does winning look like in 5 years?", placeholder: "The scale vision...", maxWords: 150, type: "textarea" },
    ],
  },
  {
    id: "pioneer",
    name: "Pioneer",
    shortName: "Pioneer",
    type: "fellowship",
    description: "Pioneer is an accelerator that finds early-stage founders anywhere in the world through a weekly tournament.",
    amount: "$50K",
    equity: "1%",
    deadline: "Weekly applications",
    location: "Global / Remote",
    stage: "Pre-seed, solo ok",
    focusAreas: ["Any sector", "Global", "Underserved founders"],
    applyUrl: "https://pioneer.app",
    color: "yellow",
    emoji: "🟡",
    tips: [
      "Pioneer selects weekly — apply now, don't wait",
      "Weekly updates are critical for ranking — show momentum",
      "Solo founders welcome — no team needed",
      "The tournament rewards consistent progress and transparency",
    ],
    questions: [
      { id: "pioneer_q1", label: "What are you building in one sentence?", placeholder: "Crisp, jargon-free description...", maxWords: 25, type: "short" },
      { id: "pioneer_q2", label: "What did you do this week to move your project forward?", placeholder: "Concrete progress this week...", maxWords: 150, type: "textarea" },
      { id: "pioneer_q3", label: "What is your goal for next week?", placeholder: "One specific deliverable...", maxWords: 100, type: "textarea" },
      { id: "pioneer_q4", label: "Why will this be big?", placeholder: "The scale thesis...", maxWords: 150, type: "textarea" },
      { id: "pioneer_q5", label: "What is the URL to your project?", placeholder: "https://...", type: "url" },
    ],
  },
  {
    id: "blume",
    name: "Blume Ventures",
    shortName: "Blume",
    type: "vc",
    description: "India's leading early-stage VC, backing founders from pre-seed to Series A across consumer, SaaS, and deeptech.",
    amount: "$200K–$1M",
    equity: "8–15%",
    deadline: "Rolling",
    location: "India (Mumbai / Bangalore)",
    stage: "Pre-seed to Seed",
    focusAreas: ["India consumer", "B2B SaaS", "Proptech", "Fintech", "AI"],
    applyUrl: "https://blume.vc/apply",
    color: "indigo",
    emoji: "🟦",
    tips: [
      "Blume loves India-first problems with global potential",
      "Show deep empathy for the Indian user — not a Western copycat",
      "Proptech is a strong vertical for Blume",
      "Founder resilience and market obsession over pedigree",
    ],
    questions: [
      { id: "blume_q1", label: "Tell us about your startup — what do you do?", placeholder: "Clear product description...", maxWords: 200, type: "textarea" },
      { id: "blume_q2", label: "What is the problem and how big is the market?", placeholder: "Problem and TAM/SAM...", maxWords: 250, type: "textarea" },
      { id: "blume_q3", label: "Why is your solution unique? What's the moat?", placeholder: "Differentiation and defensibility...", maxWords: 200, type: "textarea" },
      { id: "blume_q4", label: "Tell us about the team and your founder-market fit.", placeholder: "Why you for this market...", maxWords: 200, type: "textarea" },
      { id: "blume_q5", label: "What traction do you have so far?", placeholder: "Users, revenue, pilots...", maxWords: 150, type: "textarea" },
      { id: "blume_q6", label: "How will you use the funding?", placeholder: "18-month milestones and burn plan...", maxWords: 150, type: "textarea" },
    ],
  },
  {
    id: "kalaari",
    name: "Kalaari Capital",
    shortName: "Kalaari",
    type: "vc",
    description: "Kalaari Capital is an early-stage, technology-focused VC firm that backs visionary Indian entrepreneurs.",
    amount: "$500K–$3M",
    equity: "10–20%",
    deadline: "Rolling",
    location: "India (Bangalore)",
    stage: "Seed to Series A",
    focusAreas: ["Consumer tech", "SaaS", "India", "Proptech", "AI"],
    applyUrl: "https://kalaari.com/contact",
    color: "orange",
    emoji: "🧡",
    tips: [
      "Kalaari backs founders who understand India deeply",
      "Show defensible moats — not just MVP, but vision",
      "Strong on proptech — explicitly call out India market dynamics",
      "Network into Kalaari via portfolio founders if possible",
    ],
    questions: [
      { id: "kalaari_q1", label: "Describe your company and product.", placeholder: "What you build and for whom...", maxWords: 200, type: "textarea" },
      { id: "kalaari_q2", label: "What's the market opportunity in India?", placeholder: "India-specific market analysis...", maxWords: 250, type: "textarea" },
      { id: "kalaari_q3", label: "How are you different from existing solutions?", placeholder: "Competitive differentiation...", maxWords: 200, type: "textarea" },
      { id: "kalaari_q4", label: "What is your business model?", placeholder: "Revenue streams and unit economics...", maxWords: 150, type: "textarea" },
      { id: "kalaari_q5", label: "What is your current stage and key metrics?", placeholder: "Traction, users, revenue...", maxWords: 150, type: "textarea" },
      { id: "kalaari_q6", label: "Describe your team.", placeholder: "Founders and key hires...", maxWords: 150, type: "textarea" },
    ],
  },
  {
    id: "techstars",
    name: "Techstars",
    shortName: "Techstars",
    type: "accelerator",
    description: "Techstars is a global accelerator network with programs across 100+ cities and industry verticals.",
    amount: "$120K",
    equity: "6%",
    deadline: "Program-specific (multiple/year)",
    location: "Global / India programs",
    stage: "Pre-seed to Seed",
    focusAreas: ["Any sector", "Global", "B2B", "Consumer"],
    applyUrl: "https://www.techstars.com/apply",
    color: "green",
    emoji: "⭐",
    tips: [
      "Techstars values mentor engagement — show coachability",
      "The 'why now' and 'why you' must be crystal clear",
      "Apply to India-specific programs for stronger fit",
      "References from Techstars alumni matter",
    ],
    questions: [
      { id: "ts_q1", label: "Describe your company in 140 characters.", placeholder: "Tweet-length description...", maxWords: 30, type: "short" },
      { id: "ts_q2", label: "What problem does your company solve?", placeholder: "The pain you're addressing...", maxWords: 200, type: "textarea" },
      { id: "ts_q3", label: "What is your solution?", placeholder: "How you solve it...", maxWords: 200, type: "textarea" },
      { id: "ts_q4", label: "Who are your customers and how do you reach them?", placeholder: "ICP and go-to-market...", maxWords: 200, type: "textarea" },
      { id: "ts_q5", label: "What's your current traction or stage?", placeholder: "Metrics and milestones...", maxWords: 150, type: "textarea" },
      { id: "ts_q6", label: "Tell us about your team.", placeholder: "Founders and background...", maxWords: 150, type: "textarea" },
      { id: "ts_q7", label: "Why do you want to join Techstars?", placeholder: "Specific value from the program...", maxWords: 150, type: "textarea" },
    ],
  },
  {
    id: "google_startups",
    name: "Google for Startups",
    shortName: "Google",
    type: "corporate",
    description: "Google for Startups provides cloud credits, mentorship, and access to Google's network for early-stage companies.",
    amount: "$200K cloud credits",
    equity: "0%",
    deadline: "Rolling",
    location: "Global / India",
    stage: "Any stage",
    focusAreas: ["AI/ML", "Cloud", "Any sector"],
    applyUrl: "https://startup.google.com/programs/google-for-startups-accelerator",
    color: "blue",
    emoji: "🔍",
    tips: [
      "Emphasize how you use Google Cloud / Vertex AI",
      "AI-first products get priority",
      "Show scalability on cloud infrastructure",
      "India program has separate intake — apply both",
    ],
    questions: [
      { id: "gfs_q1", label: "Describe your startup.", placeholder: "What you build...", maxWords: 200, type: "textarea" },
      { id: "gfs_q2", label: "How does your product use AI or ML?", placeholder: "AI/ML integration details...", maxWords: 200, type: "textarea" },
      { id: "gfs_q3", label: "What Google Cloud services do you use or plan to use?", placeholder: "GCP services and use cases...", maxWords: 150, type: "textarea" },
      { id: "gfs_q4", label: "What stage are you at? What are your key metrics?", placeholder: "Current metrics and milestones...", maxWords: 150, type: "textarea" },
      { id: "gfs_q5", label: "What do you need most to grow?", placeholder: "Specific growth bottleneck...", maxWords: 150, type: "textarea" },
    ],
  },
  {
    id: "microsoft_startups",
    name: "Microsoft for Startups",
    shortName: "MSFT",
    type: "corporate",
    description: "Microsoft for Startups Founders Hub provides Azure credits, GitHub, and Microsoft tools for free.",
    amount: "$150K Azure credits",
    equity: "0%",
    deadline: "Rolling",
    location: "Global",
    stage: "Any stage",
    focusAreas: ["Azure", "AI", "SaaS", "Any sector"],
    applyUrl: "https://foundershub.startups.microsoft.com",
    color: "teal",
    emoji: "🪟",
    tips: [
      "Easy to get in — low bar, high value for Azure credits",
      "AI apps using Azure OpenAI get priority and more credits",
      "Apply even if not using Azure — you can migrate",
      "Access to GitHub Enterprise and LinkedIn credits is a bonus",
    ],
    questions: [
      { id: "ms_q1", label: "Describe your product.", placeholder: "What you build...", maxWords: 150, type: "textarea" },
      { id: "ms_q2", label: "What cloud and AI services does your product use?", placeholder: "Tech stack and services...", maxWords: 150, type: "textarea" },
      { id: "ms_q3", label: "What stage is your startup?", placeholder: "Stage, team, traction...", maxWords: 100, type: "textarea" },
      { id: "ms_q4", label: "What's your target market?", placeholder: "Who you serve...", maxWords: 100, type: "textarea" },
    ],
  },
  {
    id: "500_global",
    name: "500 Global",
    shortName: "500",
    type: "accelerator",
    description: "500 Global (formerly 500 Startups) backs diverse founders globally with a focus on emerging markets.",
    amount: "$150K",
    equity: "6%",
    deadline: "Cohort-based",
    location: "Global / Emerging Markets",
    stage: "Pre-seed to Seed",
    focusAreas: ["Emerging markets", "Diverse founders", "SaaS", "Consumer", "India"],
    applyUrl: "https://500.co/apply",
    color: "red",
    emoji: "5️⃣",
    tips: [
      "500 loves underrepresented founders and emerging market plays",
      "India is a priority market — lean into it",
      "Show you understand distribution and not just product",
      "Alumni network access is the biggest value-add",
    ],
    questions: [
      { id: "500_q1", label: "What does your company do?", placeholder: "One-paragraph description...", maxWords: 150, type: "textarea" },
      { id: "500_q2", label: "What is the problem you are solving?", placeholder: "Pain point and scale...", maxWords: 200, type: "textarea" },
      { id: "500_q3", label: "What is unique about your solution?", placeholder: "Differentiation...", maxWords: 200, type: "textarea" },
      { id: "500_q4", label: "Tell us about your traction.", placeholder: "Users, revenue, growth...", maxWords: 150, type: "textarea" },
      { id: "500_q5", label: "Who is on your team?", placeholder: "Founders and background...", maxWords: 150, type: "textarea" },
      { id: "500_q6", label: "What is your funding ask and how will you use it?", placeholder: "Ask and allocation...", maxWords: 150, type: "textarea" },
    ],
  },
  {
    id: "stellaris",
    name: "Stellaris Venture Partners",
    shortName: "Stellaris",
    type: "vc",
    description: "Stellaris is an India-focused early-stage VC with a thesis around deep tech, SaaS, and consumer internet.",
    amount: "$500K–$3M",
    equity: "10–20%",
    deadline: "Rolling",
    location: "India (Bangalore / Mumbai)",
    stage: "Pre-seed to Series A",
    focusAreas: ["Deep tech", "B2B SaaS", "AI", "India", "Proptech"],
    applyUrl: "https://stellarisvp.com/contact",
    color: "purple",
    emoji: "⭐",
    tips: [
      "Stellaris has a strong proptech thesis for Indian market",
      "Show you've done deep user research — not hypothesis-driven",
      "Team quality and complementarity is highly weighted",
      "Be ready to discuss moats and defensibility deeply",
    ],
    questions: [
      { id: "st_q1", label: "Describe your startup.", placeholder: "What you do and for whom...", maxWords: 200, type: "textarea" },
      { id: "st_q2", label: "What is your insight about the Indian market that others miss?", placeholder: "India-specific insight...", maxWords: 250, type: "textarea" },
      { id: "st_q3", label: "What is your moat or defensibility?", placeholder: "Why you can't be easily copied...", maxWords: 200, type: "textarea" },
      { id: "st_q4", label: "What is your go-to-market strategy?", placeholder: "How you acquire and retain customers...", maxWords: 200, type: "textarea" },
      { id: "st_q5", label: "What are your key metrics?", placeholder: "Current traction and projections...", maxWords: 150, type: "textarea" },
      { id: "st_q6", label: "Why now and why you?", placeholder: "Timing and founder-market fit...", maxWords: 200, type: "textarea" },
    ],
  },
]

export const TYPE_LABELS: Record<ProgramType, string> = {
  fellowship: "Fellowship",
  accelerator: "Accelerator",
  vc: "VC Fund",
  grant: "Grant",
  corporate: "Corporate Program",
}

export const STATUS_LABELS: Record<ApplicationStatus, string> = {
  not_started: "Not Started",
  drafting: "Drafting",
  submitted: "Submitted",
  interviewing: "Interviewing",
  accepted: "Accepted",
  rejected: "Rejected",
}

export const STATUS_COLORS: Record<ApplicationStatus, string> = {
  not_started: "text-zinc-400 bg-zinc-800",
  drafting: "text-yellow-400 bg-yellow-900/30",
  submitted: "text-blue-400 bg-blue-900/30",
  interviewing: "text-purple-400 bg-purple-900/30",
  accepted: "text-green-400 bg-green-900/30",
  rejected: "text-red-400 bg-red-900/30",
}

export const TYPE_COLORS: Record<ProgramType, string> = {
  fellowship: "text-purple-400 bg-purple-900/20 border-purple-800",
  accelerator: "text-orange-400 bg-orange-900/20 border-orange-800",
  vc: "text-blue-400 bg-blue-900/20 border-blue-800",
  grant: "text-green-400 bg-green-900/20 border-green-800",
  corporate: "text-teal-400 bg-teal-900/20 border-teal-800",
}
